#! /usr/bin/perl -w

use News::Scan;

my $scan = new News::Scan Group      => 'comp.lang.perl.misc',
                          Spool      => '/tmp/clpm',
                          From       => 'nntp',
                          NNTPServer => 'crp-201:1234';

if (not defined $scan) {
    die "Failed to create News::Group object\n";
}
elsif ($scan->error) {
    die "Error: " . $scan->error . "\n";
}

$scan->collect;
if ($scan->error) {
    die "Error: " . $scan->error . "\n";
}

exit;
